version: '3.8'

services:
  agro-vision-server:
    container_name: agrovision-server
    restart: always
    depends_on:
      - database
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: AgroVision.Server/Dockerfile
  
  database:
    image: "postgres:latest"
    hostname: postgres
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "AgroVisionDb"
      PG_DATA: "/var/lib/postgresql/data"
